In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import statsmodels.api as sm
import matplotlib   
from sklearn.decomposition import PCA
matplotlib.rcParams['font.sans-serif'] = ['SimHei']
matplotlib.rcParams['axes.unicode_minus']=False

# 4.1

总体$$X=\begin{bmatrix}X_1\\X_2\\X_3\end{bmatrix}$$  
协方差矩阵：$$\Sigma=\begin{bmatrix}\sigma^2&&\sigma^2\rho&&0\\\sigma^2\rho&&\sigma^2&&\sigma^2\rho\\0&&\sigma^2\rho&&\sigma^2\end{bmatrix}$$  
- 计算X的主成分：
> **首先**求解特征值：$$det(\Sigma-\lambda E)=det\begin{bmatrix}\sigma^2-\lambda&&\sigma^2\rho&&0\\\sigma^2\rho&&\sigma^2-\lambda&&\sigma^2\rho\\0&&\sigma^2\rho&&\sigma^2-\lambda\end{bmatrix}=0$$
> $$\Downarrow$$
> $$(\sigma^2-\lambda)[(\sigma^2-\lambda)^2-\sigma^4(1+\rho^2)]=0 $$
> 解得特征值为：$$\left\{\begin{aligned}\lambda_1&=\sigma^2\\\lambda_2&=\sigma^2(1-\sqrt{1+\rho^2})\\\lambda_3&=\sigma^2(1+\sqrt{1+\rho^2})\end{aligned}\right.$$
> **其次**计算特征向量  
> 令特征向量$$u_i=\begin{bmatrix}u_{1i}\\u_{2i}\\u_{3i}\end{bmatrix}$$其中，i=1,2,3  
> 依次使$$(\Sigma-\lambda_iE)u_i=0$$  
> 解得特征值分别对应的特征向量为  
> **计算贡献率**  
> $$贡献率_1=\frac{\lambda_1}{\lambda_1+\lambda_2+\lambda_3}=\frac{\sigma^2}{3\sigma^2}=\frac{1}{3}$$
> $$贡献率_2=\frac{\lambda_2}{\lambda_1+\lambda_2+\lambda_3}=\frac{\sigma^2(1-\sqrt{1+\rho^2})}{3\sigma^2}=\frac{(1-\sqrt{1+\rho^2})}{3}$$
> $$贡献率_3=\frac{\lambda_3}{\lambda_1+\lambda_2+\lambda_3}=\frac{\sigma^2(1+\sqrt{1+\rho^2})}{3\sigma^2}=\frac{(1+\sqrt{1+\rho^2})}{3}$$

$\vdots$

# 4.4

In [48]:
# 读取数据
filename = 'ex4d4data.xls'
data = pd.read_excel(filename, header=None)
data

0      1      2      3  4
0  1.000  0.000  0.000  0.000  0
1  0.577  1.000  0.000  0.000  0
2  0.509  0.599  1.000  0.000  0
3  0.387  0.389  0.436  1.000  0
4  0.462  0.322  0.426  0.523  1

In [49]:
# 相关系数矩阵
R = data.values

m, n = R.shape

k = 0
for i in range(m):
    for j in range(k, n):
        R[i, j] = R[j, i]
        
print(R)
# 特征值、特征向量
values, vectors = np.linalg.eig(R)

[[1.    0.577 0.509 0.387 0.462]
 [0.577 1.    0.599 0.389 0.322]
 [0.509 0.599 1.    0.436 0.426]
 [0.387 0.389 0.436 1.    0.523]
 [0.462 0.322 0.426 0.523 1.   ]]


In [50]:
values

array([2.85671099, 0.80916372, 0.34294995, 0.53967524, 0.4515001 ])

In [51]:
vectors

array([[ 0.46360519,  0.24033901,  0.45126217,  0.61170545, -0.38663456],
       [ 0.45710783,  0.50930473, -0.67622331, -0.17818949, -0.20647436],
       [ 0.47017564,  0.26044828,  0.40000721, -0.33505645,  0.66244469],
       [ 0.42145876, -0.5256649 ,  0.17559859, -0.54076277, -0.47200602],
       [ 0.42122445, -0.58196989, -0.38502448,  0.43517554,  0.38243876]])

In [55]:
Y = np.zeros((m, n))
for i in range(m):
    for j in range(n):
        Y[j, i] = R[j]@vectors[:, i]
Y

array([[ 1.32438605,  0.19447361,  0.15476034,  0.33012228, -0.17456554],
       [ 1.30582496,  0.41211091, -0.23191075, -0.09616446, -0.09322319],
       [ 1.34315591,  0.2107453 ,  0.13718245, -0.18082167,  0.29909384],
       [ 1.20398589, -0.42534897,  0.06022153, -0.29183628, -0.21311076],
       [ 1.20331653, -0.47090892, -0.13204412,  0.23485347,  0.17267114]])

In [56]:
# 主成分分析
pca = PCA(n_components=5)
pca.fit(R)

PCA(n_components=5)

In [57]:
pca.transform(R)# 降维后的结果

array([[ 2.15763994e-01,  3.30558946e-01, -1.71843116e-01,
        -1.58738607e-01,  0.00000000e+00],
       [ 4.26012346e-01, -9.72942251e-02, -9.67407120e-02,
         2.31977304e-01,  0.00000000e+00],
       [ 2.35386067e-01, -1.79088201e-01,  3.03286854e-01,
        -1.37075962e-01,  2.22044605e-16],
       [-4.16812013e-01, -2.90766259e-01, -2.08431201e-01,
        -6.71094848e-02,  0.00000000e+00],
       [-4.60350394e-01,  2.36589740e-01,  1.73728174e-01,
         1.30946749e-01,  0.00000000e+00]])

In [35]:
k = 1
for i in pca.explained_variance_ratio_: # 降维后的各主成分的方差贡献率
    print(f'第{k}主成分的贡献率为{i:.2%}')
    k += 1

第1主成分的贡献率为52.10%
第2主成分的贡献率为22.68%
第3主成分的贡献率为15.92%
第4主成分的贡献率为9.30%
第5主成分的贡献率为0.00%


In [36]:
pca.explained_variance_ # 降维后的各主成分的方差值

array([1.67275490e-01, 7.28319224e-02, 5.11241954e-02, 2.98629921e-02,
       1.66215245e-33])

# 4.5

In [39]:
filename = 'ex4d5data.xls'
data = pd.read_excel(filename, header=None, names=['省市', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8',] )
data.head()

省市    x1     x2    x3    x4     x5     x6    x7     x8
0        shanxi  8.35  23.53  7.51  8.62  17.42  10.00  1.04  11.21
1     neimenggu  9.25  23.75  6.61  9.19  17.77  10.48  1.72  10.51
2         jilin  8.19  30.50  4.72  9.78  16.28   7.60  2.52  10.32
3  heilongjiang  7.73  29.20  5.42  9.43  19.29   8.49  2.52  10.00
4         henan  9.42  27.93  8.20  8.14  16.17   9.42  1.55   9.76

In [45]:
X = data[['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8']].values

R = np.corrcoef(X, rowvar=False)
R

array([[ 1.        ,  0.33364671, -0.05453868, -0.06125369, -0.28936059,
         0.19879627,  0.34869847,  0.31867736],
       [ 0.33364671,  1.        , -0.02290183,  0.39893102, -0.15630387,
         0.71113407,  0.41359462,  0.83495175],
       [-0.05453868, -0.02290183,  1.        ,  0.53332919,  0.49676279,
         0.03282961, -0.1390858 , -0.2583581 ],
       [-0.06125369,  0.39893102,  0.53332919,  1.        ,  0.69842442,
         0.4679173 , -0.17127417,  0.31275728],
       [-0.28936059, -0.15630387,  0.49676279,  0.69842442,  1.        ,
         0.28012915, -0.20827738, -0.08123414],
       [ 0.19879627,  0.71113407,  0.03282961,  0.4679173 ,  0.28012915,
         1.        ,  0.41682128,  0.70158588],
       [ 0.34869847,  0.41359462, -0.1390858 , -0.17127417, -0.20827738,
         0.41682128,  1.        ,  0.39886792],
       [ 0.31867736,  0.83495175, -0.2583581 ,  0.31275728, -0.08123414,
         0.70158588,  0.39886792,  1.        ]])

In [46]:
# 主成分分析
pca = PCA(n_components=len(R))
pca.fit(R)

Y_new = pca.transform(R)# 降维后的结果

k = 1
for i in pca.explained_variance_ratio_: # 降维后的各主成分的方差贡献率
    print(f'第{k}主成分的贡献率为{i:.2%}')
    k += 1

var = pca.explained_variance_ # 降维后的各主成分的方差值

第1主成分的贡献率为68.81%
第2主成分的贡献率为21.23%
第3主成分的贡献率为5.63%
第4主成分的贡献率为2.87%
第5主成分的贡献率为1.05%
第6主成分的贡献率为0.33%
第7主成分的贡献率为0.07%
第8主成分的贡献率为0.00%
